language: android

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - sys-img-armeabi-v7a-google_apis-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-android-support

jdk: oraclejdk8

addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta --depth 1

script:
  - ./flutter/bin/flutter doctor
  # builds Android APK
  # - ./flutter/bin/flutter -v build apk
  # tests
  # - ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache